# Setup
title:               Jeong Hyunho
tagline:             ''
description:         'A collection of notes.<br>Made by <a href="https://twitter.com/jeong_hyunho" target="_blank">@hyunho_jeong</a>.'
url:                 https://github.com/JeongHyunho/JeongHyunho.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jeong Hyunho
  url:               https://twitter.com/jeong_hyunho
  email:             hyunho_jeong@kaist.ac.kr
  twitter:           jeong_hyunho

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
